module.exports = {
  docs: {
    Introducción: ['00-intro'],
    'Módulo 1 - Introducción a la programación y Programación Estructurada': [
      'modulo-1/clase-01',
      'modulo-1/clase-02',
      'modulo-1/clase-03',
      'modulo-1/clase-04',
      'modulo-1/clase-05',
      'modulo-1/clase-06',
      'modulo-1/clase-07',
      'modulo-1/clase-08',
      'modulo-1/clase-09',
      'modulo-1/clase-10',
      'modulo-1/clase-11',
      'modulo-1/clase-12',
      'modulo-1/clase-13',
    ],
    'Módulo 2 - Programacion Orientada a Objetos': [
      'modulo-2/clase-14',
      'modulo-2/clase-15',
      'modulo-2/clase-16',
      'modulo-2/clase-17',
      'modulo-2/clase-18',
      'modulo-2/clase-19',
      'modulo-2/clase-20',
      'modulo-2/clase-21',
      'modulo-2/clase-22',
      'modulo-2/clase-23',
      'modulo-2/clase-24',
      'modulo-2/clase-25',
    ],
  },
}
